### ISSUE TITLE
Bump to Ext. H

### ISSUE THREAD

**Issue by Honoka55** [ambar/fangyanzi#2]
41 characters in the document have been encoded in CJK Ext. H:
- ⿰冫兆.svg → 𱐃`U+31403`
- ⿰冫頁.svg → 𱐇`U+31407`
- ⿰口廹.svg → 𱓆`U+314C6`
- ⿰口恁.svg → 𱓶`U+314F6`
- ⿰口様.svg → 𱕇`U+31547`
- ⿰土匡.svg → 𱖟`U+3159F`
- ⿰土干.svg → 𱖇`U+31587`
- ⿰土非.svg → 𱖾`U+315BE`
- ⿰女能.svg → 𱙦`U+31666`
- ⿰扌欒.svg → 𱡖`U+31856`
- ⿰月乃.svg → 𱼁`U+31F01`
- ⿰月戛.svg → 𱼕`U+31F15`
- ⿰火勒.svg → 𱬀`U+31B00`
- ⿰犭活.svg → 𱮏`U+31B8F`
- ⿰用力.svg → 𱐮`U+3142E`
- ⿰目契.svg → 𱳃`U+31CC3`
- ⿰目楚.svg → 𱳋`U+31CCB`
- ⿰石恩.svg → 𱴨`U+31D28`
- ⿰禺欠.svg → 𱤸`U+31938`
- ⿰禾郞.svg → 𱶞`U+31D9E`
- ⿰米堯.svg → 𱹞`U+31E5E`
- ⿰米意.svg → 𱹤`U+31E64`
- ⿰纟些.svg → 𱺤`U+31EA4`
- ⿰虫⿱死肉.svg → 𲀊`U+3200A`
- ⿰虫厚.svg → 𱿳`U+31FF3`
- ⿰虫戛.svg → 𲀁`U+32001`
- ⿰虫施.svg → 𱿸`U+31FF8`
- ⿰虫革.svg → 𱿲`U+31FF2`
- ⿰赤兒.svg → 𲃇`U+320C7`
- ⿰金而.svg → 𲇋`U+321CB`
- ⿱不多.svg → 𱍚`U+3135A`
- ⿱大男.svg → 𱘲`U+31632`
- ⿱屈衣.svg → 𲀷`U+32037`
- ⿱未母.svg → 𱥛`U+3195B`
- ⿱莫用.svg → 𱰠`U+31C20`
- ⿱非射.svg → 𲊙`U+32299`
- ⿱髟任.svg → 𲌛`U+3231B`
- ⿸尸妥.svg → 𱚺`U+316BA`
- ⿸尸查.svg → 𱚼`U+316BC`
- ⿸疒壬.svg → 𱱋`U+31C4B`
- ⿻丅⿱从人.svg → 𱍕`U+31355`

Hope you can map them to the correct code points. Thank you.

**Comment by ambar** [comment]
Thanks a lot!
